version: '3.4'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  workspace:
    build:
      context: ./workspace
      dockerfile: Dockerfile
      args:
        - PUID=${WORKSPACE_PUID}
        - PGID=${WORKSPACE_PGID}
        - TZ=${WORKSPACE_TIMEZONE}
        - COMPOSER_PACKAGIST_URL=${WORKSPACE_COMPOSER_PACKAGIST_URL}
    volumes:
      - ${APP_CODE_PATH}:${APP_CONTAINER_PATH}
    ports:
      - "${WORKSPACE_HTTP_PORT}:8000"
    tty: true
    networks:
      - backend

  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    volumes:
      - ${APP_CODE_PATH}:${APP_CONTAINER_PATH}
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_PATH}:${APP_CONTAINER_PATH}
      - ${DATA_PATH}/nginx/log:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - backend

  minio:
    build:
      context: ./minio
      dockerfile: Dockerfile
    volumes:
      - ${DATA_PATH}/minio/data:/export
      - ${DATA_PATH}/minio/config:/root/.minio
    ports:
      - "${MINIO_HTTP_PORT}:9000"
    environment:
      - MINIO_ACCESS_KEY=access
      - MINIO_SECRET_KEY=secretkey
    networks:
      - backend

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
      args:
        - TZ=${MYSQL_TIMEZONE}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend